version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
