version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ".env"
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL
    volumes:
      - .:/src
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    depends_on:
      - db
