# Generated by Django 3.1 on 2020-08-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('link', models.URLField(verbose_name='Link')),
                ('comments', models.URLField(verbose_name='Comments Link')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Published Date')),
                ('guid', models.IntegerField(default=0, verbose_name='GUID')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'db_table': 'feeds_items',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Category')),
                ('items', models.ManyToManyField(related_name='categories', to='feeds.Item')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'feeds_categories',
            },
        ),
    ]
